include ".buildkit/.scalafmt.shared.conf"

version = "3.10.7"

runner.dialect = "scala213"

// In 3.10 this works more like "keep" than actual "keep"
newlines.infix.termSite.style = none
newlines.infix.typeSite.style = none // not sure about this one

# !!! TODO !!! Update styles in the generator to match scalafmt config
#  - Maybe make a separate config for these files, that has two lines before method names, see https://scalameta.org/scalafmt/docs/configuration.html#fileoverride
#  - Does this exclusion actually work? IntelliJ seems to ignore it
project.excludePaths = [
  "glob:**/src/*/scala-3/**",
  "glob:**/src/main/scala/com/raquo/laminar/defs/**",
  "glob:**/project/VersionHelper.scala",
]
